### ISSUE TITLE
Time class deprecated in CakePHP 4.3.0

### ISSUE THREAD

**Issue by mrothauer** [dereuromark/cakephp-feed#15]
I upgraded my application to CakePHP 4.3.0

Feed\View\RssView::time() - ROOT/vendor/dereuromark/cakephp-feed/src/View/RssView.php, line 145
Feed\View\RssView::_prepareOutput() - ROOT/vendor/dereuromark/cakephp-feed/src/View/RssView.php, line 294
Feed\View\RssView::_serialize() - ROOT/vendor/dereuromark/cakephp-feed/src/View/RssView.php, line 234
Feed\View\RssView::render() - ROOT/vendor/dereuromark/cakephp-feed/src/View/RssView.php, line 179
include - ROOT/templates/layout/rss/default.php, line 13

**Comment by dereuromark** [comment]
You can make a PR with suggested changes.

Also note that plugin deprecations should never show in your code, best to also always ignore those for your app, so only relevant issues are displayed.
You cannot control core/plugins directly, so those showing up isnt a good thing for your application :)
