### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-feed#19]
Things to be fixed up before:

- [x] $this->viewBuilder()->setOptions(compact('serialize')); instead of _serialize data element?
- [ ] ...?

Until then use `^3.0.0@RC` as version constraint.

**Comment by mrothauer** [comment]
@dereuromark FYI: I am currently upgrading a codebase to CakePHP 5 with your FeedPlugin and so far everything is working well.
see https://github.com/anstiftung/mapped-repair-events/pull/137

**Comment by dereuromark** [comment]
Great to hear
