### ISSUE TITLE
Wrong documentation on how to enable serialization / issue with RssView::loadHelpers()

### ISSUE THREAD

**Issue by mixable** [dereuromark/cakephp-feed#20]
The [documentation](https://github.com/dereuromark/cakephp-feed/blob/master/docs/View/Rss.md) says, it's necessary to use the following code to serialize the output:

```php
$this->set(['data' => $data, '_serialize' => 'data']);
```

In the past (CakePHP < 5) this works as expected. But the latest version of SerializedView (CakePHP 5.0.5) uses `$this->getConfig()` to check for the serialized content. Now I had to use the following code to make the serialization work:

```php
$this->viewBuilder()->setOption('serialize', 'data');
$this->set('data', $data);
```

Maybe the docs need to be updated for the latest version which is now compatible with CakePHP 5?

Maybe there is also an issue in `RssView::loadHelpers()`. This method calls `parent::loadHelpers()` only when using `$this->set(['data' => $data, '_serialize' => 'data']);`. But its parent in `SerializedView::loadHelpers()` does not. The extended SerializedView performs a similar check to call `parent::loadHelpers()`, but it uses `$this->getConfig('serialize')`. So this only works with `$this->viewBuilder()->setOption('serialize', 'data')`.

I think updating the docs as mentioned above and removing `RssView::loadHelpers()` will do the trick.

**Comment by dereuromark** [comment]
An update to docs as PR would be great

**Comment by dereuromark** [comment]
Can you check if https://github.com/dereuromark/cakephp-feed/commit/d691828f3ff02316a323329fb87fa0dd9667ae79 is enough?
Otherwise please open a PR with further changes/fixes.

**Comment by mixable** [comment]
Yes, this look's good. With these changes, the serialization now works as mentioned in the docs. Thank you!
